# Generated by Django 2.2.12 on 2020-08-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('departamento', models.CharField(max_length=150)),
                ('funcao', models.CharField(max_length=150)),
            ],
        ),
    ]
